---
title: "Penjelasan"
author: "Ikang Fadhli"
date: "Update 3 November 2020"
output: 
  github_document:
    pandoc_args: --webtex
---

```{r setup, include=FALSE}
rm(list=ls())
setwd("~/Documents/Live-Session-Nutrifood-R/LEFO Market Research/EXPSS")
knitr::opts_chunk$set(echo = TRUE)
```

# _Learning Forum Market Research_

## _Dear All,_

Kita telah menyelesaikan _training_ `expss` hari pertama. Kita telah mempelajari bagaimana:

1. Membuat tabulasi frekuensi.
1. Membuat cross tabulasi.
1. Melakukan uji signifkansi dari cross tabulasi.
1. Mengekspor tabulasi dari __R__ ke _Excel file_ (`.xlsx`).

Sekarang pada sesi kedua, kita akan membahas `2` hal, yakni:

1. _Filter_.
1. _Recode_.

Untuk melakukannya, saya akan menggunakan prinsip `tidy` di __R__ dengan perintah _pipe_ (`%>%`).

## _Dataset_ untuk _training_

_Dataset_ training akan tetap menggunakan data yang sama, yakni: `dataset latihan.xlsx`.

---

# Materi _Training_


## Prinsip dasar `library(expss)`

Skrip pada `library(expss)` selalu menggunakan _pipe_ pada `tidyverse` (` %>% `).

Berikut adalah alur pengerjaannya:

1. Tabulasi dimulai dengan memanggil dataset.
1. Memanggil variabel yang hendak dihitung dengan `tab_cells(nama_variabel)`.
1. Jika hendak melakukan _cross tabulasi_, tambahkan perintah `tab_cols(nama_variabel)` sesuai dengan variabel yang hendak disilangkan.
1. Jika hendak melakukan _drill down_ pada baris, tambahkan perintah `tab_rows(nama_variabel)` sesuai dengan variabel yang hendak disilangkan.
1. Panggil perintah untuk menghitung persentase atau _real number_. Untuk persentase, bisa menggunakan perintah `tab_stat_cpct()`. Untuk _real number_, bisa menggunakan perintah `tab_stat_cases()`.
1. Jika hendak melakukan uji beda dua proporsi pada _cross tabulasi_, `tambahkan tab_last_sig_cpct()` atau `tab_last_sig_cases()`.
1. Akhiri dengan `tab_pivot()`.

## Prinsip dasar _filter_

Untuk melakukan _filtering data_, kita akan menggunakan perintah `filter()` berisi variabel dan kondisi yang kita inginkan.

Beberapa _conditional_ yang perlu diketahui dan biasa digunakan untuk data _survey_ antara lain:

- `==` digunakan pada saat mewajibkan kondisi yang __sama__.
- `!=` digunakan pada saat mewajibkan kondisi yang __tidak sama__.
- `|` digunakan untuk __OR__.
- `&` digunakan untuk __AND__.

## Prinsip dasar _recode_

Untuk melakukan _recode_ dari variabel yang ada, kita akan menggunakan perintah `mutate()` berisi formula yang akan kita hitung. Biasanya proses _recode_ berasal dari _conditional_ dari variabel lain.

Contohnya adalah membuat kategori `T2B`, `Netral`, dan `B2B` dari pertanyaan berskala `1` sampai `6`. Untuk melakukannya, kita bisa menggunakan perintah `case_when()`.

## __R__ _Script_

Semua _script_ yang dibutuhkan bisa di-_download_ di _folder_ ini dengan judul `skrip LEFO.R`.

__Silakan di-_download_ terlebih dahulu skripnya _yah_. Kita akan melanjutkan dari sana.__
