---
title: "Welcome!"
output: github_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

_Repositories_ ini berisi _R Markdown_ penyelesaian dari beberapa kasus yang diberikan pada saat ___optimization training___ oleh __FINANMOS ITB__ 2021.

Saya menggunakan __R__ untuk membuat model _optimization_ dan di-_solve_ dengan _engine_ yang tersedia di `library(ompr)`.

Agak berbeda dengan _libraries_ yang akan digunakan saat _training_ dengan __FINANMOS ITB__ kelak namun tetap menghasilkan hasil yang sama. Karena persoalan yang pentingnya adalah bagaimana memodelkan masalah _real_ ke permodelan matematikanya. Jika sudah termodelkan, akan mudah dimasukkan ke berbagai _libraries_ yang ada di __R__.

> ___Silakan Anda mendownload file___ `Training Notes Optimization.pdf` ___yang ada di folder ini___.

## __Discord__

Punya akun _Discord_? Kalau belum, silakan _download apps_-nya di [sini](https://discord.com/).

_Available_ untuk __iOS__, __Android__, __Windows__, dan __Linux__.

_Join discord_ __Nutrifood x R__ di _link_ [berikut ini](https://discord.gg/zy9XJgsf).

---

Selamat belajar.

_Feel free to discuss_.

_Created by:_ [Ikang Fadhli](https://ikanx101.com/)

_Last update:_ `r Sys.time()`